//=======================================================================
// ï¿½ï¿½ï¿½×‚ï¿½ï¿½ï¿½Aï¿½Eï¿½ï¿½ï¿½È‚Ç‚Ì“ï¿½ï¿½ï¿½pï¿½Xï¿½Nï¿½ï¿½ï¿½vï¿½g
// FPSControllerï¿½É•tï¿½ï¿½ï¿½ï¿½
//=======================================================================
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Action : MonoBehaviour
{
    private GameObject DropWeapon;      
    DropGun DGScript;
    ChangeEquip CEScript;                   // [ChangeEquip]ï¿½pï¿½Ì•Ïï¿½
    LoadGunPrefab LGPScript;
    public bool actionFlg;
    GameObject ObjectInfo;
    GameObject tmp;
    public AiryUIAnimationManager UIEvent;
    bool isCalledOnce = false;

    void Start()
    {
        CEScript = GetComponent<ChangeEquip>();
        LGPScript = GetComponent<LoadGunPrefab>();
    }

    void Update()
    {
        // ï¿½Eï¿½ï¿½ï¿½Æ‚ï¿½ï¿½Ìƒeï¿½Lï¿½Xï¿½gï¿½p
        if(actionFlg && !isCalledOnce)
        {
            isCalledOnce = true;
            Debug.Log(UIEvent);
            UIEvent.ShowMenu();
        } else if(!actionFlg && isCalledOnce) {
            UIEvent.HideMenu();
            isCalledOnce = false;
        }

        if(Input.GetKeyDown(KeyCode.E) && actionFlg)
        {
            // ï¿½ó” ï¿½ï¿½ï¿½
            if(ObjectInfo.tag == "DropBox"){BoxAction(ObjectInfo);}
            
            // ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½eï¿½Ìï¿½ï¿½ï¿½
            if(ObjectInfo.tag == "DropGun"){WeaponAction(ObjectInfo);}

            actionFlg = false;
        }
    }

    void BoxAction(GameObject Object)
    {
        // ï¿½ó” ‚ï¿½ï¿½íœ
        Destroy(Object.gameObject);

        // DropItemï¿½ğ¶ï¿½
        var IBScript = Object.GetComponent<ItemBox>();
        IBScript.Open();
    }

    void WeaponAction(GameObject Object)
    {
        // DropItemï¿½ï¿½ï¿½æ“¾
        var DIScript = Object.GetComponent<DropGun>();

        // ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½é•ï¿½ï¿½ğ‘•”ï¿½ï¿½ï¿½ï¿½ï¿½
        // ï¿½ï¿½DropWeaponï¿½É‚Íï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½ï¿½
        DropWeapon = CEScript.GetWeapon(Object);

        // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ìê‡ï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        if(DropWeapon != null)
        {
            // ï¿½ï¿½getWeaponï¿½É‚Íï¿½É“ï¿½ï¿½ï¿½é•ï¿½ï¿½
		    GameObject getWeapon = Instantiate<GameObject>(Object);
            getWeapon.name = DIScript.WeaponInfo.name;

            // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÌŒï¿½ï¿½ï¿½
            GunInfo getGIScript = getWeapon.GetComponent<GunInfo>();
            GunController dropGCScript = DropWeapon.GetComponent<GunController>();

            // ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½é•ï¿½ï¿½ï¿½ï¿½íœ
            Destroy(Object.gameObject);

            // ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½Ûï¿½
            var RankInfo            = dropGCScript.gunRank;          // ï¿½ï¿½ï¿½íƒ‰ï¿½ï¿½ï¿½N
            var TypeInfo            = dropGCScript.gunType;          // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            var SlotInfo            = dropGCScript.skillSlot;        // ï¿½Xï¿½Lï¿½ï¿½ï¿½Xï¿½ï¿½ï¿½bï¿½gï¿½ï¿½
            var MaxMagazineInfo     = dropGCScript.MagazineSize;     // ï¿½Pï¿½}ï¿½Kï¿½Wï¿½ï¿½ï¿½ÌƒTï¿½Cï¿½Y
            var remMagazineInfo     = dropGCScript.Ammo;             // ï¿½}ï¿½Kï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½Ìcï¿½eï¿½ï¿½
            var MaxAmmoInfo         = dropGCScript.AmmoSize;         // ï¿½\ï¿½ï¿½ï¿½eï¿½ï¿½ï¿½Tï¿½Cï¿½Y
            var remAmmoInfo         = dropGCScript.remAmmo;          // ï¿½\ï¿½ï¿½ï¿½eï¿½ï¿½
            var DamageInfo          = dropGCScript.Damage;           // ï¿½Î—ï¿½
            var shootIntervalInfo   = dropGCScript.shootInterval;    // ï¿½ËŒï¿½ï¿½ÔŠu
            var reloadIntervalInfo  = dropGCScript.reloadInterval;   // ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½hï¿½Xï¿½sï¿½[ï¿½h
            var PowerInfo           = dropGCScript.bulletPower;      // ï¿½eï¿½Ì”ï¿½Î‚ï¿½ï¿½ï¿½
            var EXPInfo             = dropGCScript.GunEXP;           // ï¿½eï¿½ÌŒoï¿½ï¿½ï¿½l

            // ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½ï¿½ï¿½ï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½(dropGCScript <= getGIScript)
            CEScript.ChangeGunConInfo(dropGCScript,getGIScript,1);

            // ï¿½Eï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            getGIScript.gunRank        = RankInfo;
            getGIScript.gunType        = TypeInfo;
            getGIScript.skillSlot      = SlotInfo;
            getGIScript.MagazineSize   = MaxMagazineInfo;
            getGIScript.remMagazine    = remMagazineInfo;
            getGIScript.ammoMax        = MaxAmmoInfo;
            getGIScript.remAmmo        = remAmmoInfo;
            getGIScript.Damage         = DamageInfo;
            getGIScript.shootInterval  = shootIntervalInfo;
            getGIScript.reloadInterval = reloadIntervalInfo;
            getGIScript.bulletPower    = PowerInfo;
            getGIScript.GunEXP         = EXPInfo;
        } else {
            // ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½é•ï¿½ï¿½ï¿½ï¿½íœ
            Destroy(Object.gameObject);
        }     
    }

    
    void OnTriggerEnter(Collider other)
    {
        if( other.gameObject.tag == "DropBox" ||
            other.gameObject.tag == "DropGun")
        {
            ObjectInfo = other.gameObject;
            actionFlg = true;
        }
    }

    void OnTriggerExit(Collider other)
    {
        actionFlg = false;
    }
}
